name: iOS CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build iOS App (.ipa)
    runs-on: macos-latest

    env:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ruby and Bundler
        run: |
          gem install bundler
          bundle init || true

      - name: Install Fastlane
        run: |
          gem install fastlane -NV
          mkdir -p fastlane
          echo "opt_out_usage" > fastlane/Fastfile || true

      - name: Verify Fastlane version
        run: fastlane --version

      - name: Run Fastlane build
        run: |
          cd fastlane
          cat <<'RUBY' > Fastfile
          default_platform(:ios)

          platform :ios do
            desc "Build unsigned IPA for CI"
            lane :ci_build do
              build_app(
                project: "GestorProyectosHG.xcodeproj",
                scheme: "GestorProyectosHG",
                export_method: "ad-hoc",
                skip_signing: true,
                output_directory: "output",
                output_name: "GestorProyectosHG.ipa"
              )
            end
          end
          RUBY

          bundle exec fastlane ios ci_build

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: GestorProyectosHG-ipa
          path: |
            fastlane/output/**/*.ipa
            output/**/*.ipa
            build/**/*.ipa
          if-no-files-found: warn
